import { StoryArt, hasIllustration } from "./StoryArt";
import {
  CalendarDays,
  Flower2,
  Sun,
  CloudSun,
  Cloud,
  CloudRain,
  Snowflake,
  Wind,
  CloudFog,
  Shirt,
  Users,
  Smile,
  Star,
  BookOpen,
  Leaf,
  Apple,
  Blocks,
  Utensils,
  Moon,
  Sprout,
  Heart,
  Umbrella,
  Footprints,
  Hand,
  Settings,
  Home,
  ArrowLeft,
  Maximize,
  Minimize,
  Check,
  ChevronRight,
  PartyPopper,
  RotateCcw,
  X,
  Plus,
  Minus,
  Glasses,
} from "lucide-react";
const icons: Record<string, typeof Sun> = {
  calendar: CalendarDays,
  season: Leaf,
  weather: CloudSun,
  clothing: Shirt,
  attendance: Users,
  emotions: Smile,
  helper: Star,
  summary: BookOpen,
  Primăvara: Flower2,
  Vara: Sun,
  Toamna: Leaf,
  Iarna: Snowflake,
  Însorit: Sun,
  "Parțial noros": CloudSun,
  Înnorat: Cloud,
  Ploaie: CloudRain,
  Ninsoare: Snowflake,
  Vânt: Wind,
  Ceață: CloudFog,
  Cald: Sun,
  Răcoare: Wind,
  Frig: Snowflake,
  Tricou: Shirt,
  Bluză: Shirt,
  Pantaloni: Footprints,
  Rochiță: Shirt,
  Geacă: Shirt,
  "Haină groasă": Shirt,
  Căciulă: Glasses,
  Șapcă: Glasses,
  Pantofi: Footprints,
  Cizme: Footprints,
  Umbrelă: Umbrella,
  Fular: Wind,
  Mănuși: Hand,
  "Bună dimineața": Sun,
  Activitate: Sprout,
  Gustare: Apple,
  Joacă: Blocks,
  Masa: Utensils,
  Odihnă: Moon,
  settings: Settings,
  home: Home,
  back: ArrowLeft,
  fullscreen: Maximize,
  exit: Minimize,
  check: Check,
  next: ChevronRight,

  party: PartyPopper,
  reset: RotateCcw,
  close: X,
  plus: Plus,
  minus: Minus,
  heart: Heart,
};
export function Icon({ name, size = 32 }: { name: string; size?: number }) {
  if (size >= 26 && hasIllustration(name))
    return <StoryArt name={name} size={size} />;
  const I = icons[name] || Heart;
  return <I size={size} strokeWidth={1.7} aria-hidden="true" />;
}
export function Face({
  emotion = "Vesel",
  size = 84,
}: {
  emotion?: string;
  size?: number;
}) {
  return <StoryArt name={emotion} size={size} className="storybook-face" />;
}
